=== jilopeza/SectorCode/ServicesHSM/src/main/resources/hsm-servers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/hsm-servers"
	xmlns:tns="http://www.example.org/hsm-servers" attributeFormDefault="unqualified" elementFormDefault="unqualified">

	<complexType name="ApiHSMConfig">
		<sequence>
			<element name="General" type="tns:general"></element>
			<element name="Servers" type="tns:servers"></element>
		</sequence>
	</complexType>

	<complexType name="hsmServer">
		<sequence>
			<element name="id" type="string"></element>
			<element name="classModelName" type="string"></element>
			<element name="modelName" type="string"></element>
			<element name="classRequestName" type="string"></element>
			<element name="classResponseName" type="string"></element>
			<element name="idLMK" type="int"></element>
			<element name="lenHeader" type="int"></element>
			<element name="ip" type="string"></element>
			<element name="port" type="int"></element>
			<element name="connectionType" type="string"></element>
			<element name="timeout" type="int"></element>
			<element name="intervalEcho" type="int"></element>
			<element name="retriesNumber" type="int"></element>
			<element name="balanceType" type="string"></element>
			<element name="percentWork" type="int"></element>
			<element name="environmentType" type="string"></element>
			<element name="version" type="int"></element>
		</sequence>
	</complexType>

	<complexType name="servers">
		<sequence>
			<element name="hsmServer" type="tns:hsmServer" maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="deployment">
		<sequence>
			<element name="hilos" type="int"></element>
			<element name="llamadas" type="int"></element>
		</sequence>
	</complexType>

	<complexType name="pool">
		<sequence>
			<element name="name" type="string"></element>
			<element name="min" type="int"></element>
			<element name="max" type="int"></element>
			<element name="interval" type="int"></element>
			<element name="validate" type="boolean"></element>
			<element name="containment" type="boolean"></element>
			<element name="timeDestroyConnect" type="int"></element>
			<element name="timeout" type="int"></element>
			<element name="connectTimeout" type="int"></element>
		</sequence>
	</complexType>

	<complexType name="general">
		<sequence>
			<element name="deployment" type="tns:deployment"></element>
			<element name="pool" type="tns:pool"></element>
		</sequence>
	</complexType>

	<element name="ApiHSMConfig" type="tns:ApiHSMConfig"></element>
</schema>

=== jilopeza/SectorCode/ServicesHSM/src/main/resources/hsm-servers.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ApiHSMConfig xmlns:tns="http://www.example.org/hsm-servers"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/hsm-servers hsm-servers.xsd">

	<General>
		<deployment>
			<hilos>0</hilos>
			<llamadas>0</llamadas>
		</deployment>
		<pool>
			<name>name</name>
			<min>0</min>
			<max>0</max>
			<interval>0</interval>
			<validate>true</validate>
			<containment>true</containment>
			<timeDestroyConnect>0</timeDestroyConnect>
			<timeout>0</timeout>
			<connectTimeout>0</connectTimeout>
		</pool>
	</General>
	<Servers>
		<hsmServer>
			<id>100</id>
			<classModelName>com.novatronic.components.hsm.thales.HSMThales</classModelName>
			<modelName>HSM THALES 9000</modelName>
			<classRequestName>com.novatronic.components.hsm.thales.HSMThalesCommand9000</classRequestName>
			<classResponseName>com.novatronic.components.hsm.thales.HSMThalesResponse9000</classResponseName>
			<idLMK>0</idLMK>
			<lenHeader>4</lenHeader>
			<ip>172.29.43.164</ip>
			<port>1500</port>
			<connectionType>FAST_CONNECT</connectionType>
			<timeout>30</timeout>
			<intervalEcho>60</intervalEcho>
			<retriesNumber>3</retriesNumber>
			<balanceType>BALANCE_AUTO</balanceType>
			<percentWork>100</percentWork>
			<environmentType>ENV_PRODUCTION</environmentType>
			<version>9000</version>
		</hsmServer>

		<hsmServer>
			<id>200</id>
			<classModelName>com.novatronic.components.hsm.thales.HSMThales</classModelName>
			<modelName>HSM THALES 9000</modelName>
			<classRequestName>com.novatronic.components.hsm.thales.HSMThalesCommand9000</classRequestName>
			<classResponseName>com.novatronic.components.hsm.thales.HSMThalesResponse9000</classResponseName>
			<idLMK>0</idLMK>
			<lenHeader>4</lenHeader>
			<ip>172.29.43.164</ip>
			<port>1500</port>
			<connectionType>FAST_CONNECT</connectionType>
			<timeout>30</timeout>
			<intervalEcho>60</intervalEcho>
			<retriesNumber>3</retriesNumber>
			<balanceType>BALANCE_AUTO</balanceType>
			<percentWork>100</percentWork>
			<environmentType>ENV_PRODUCTION</environmentType>
			<version>9000</version>
		</hsmServer>

		<hsmServer>
			<id>300</id>
			<classModelName>com.novatronic.components.hsm.thales.HSMThales</classModelName>
			<modelName>HSM THALES 9000</modelName>
			<classRequestName>com.novatronic.components.hsm.thales.HSMThalesCommand9000</classRequestName>
			<classResponseName>com.novatronic.components.hsm.thales.HSMThalesResponse9000</classResponseName>
			<idLMK>0</idLMK>
			<lenHeader>4</lenHeader>
			<ip>172.29.43.164</ip>
			<port>1500</port>
			<connectionType>FAST_CONNECT</connectionType>
			<timeout>30</timeout>
			<intervalEcho>60</intervalEcho>
			<retriesNumber>3</retriesNumber>
			<balanceType>BALANCE_AUTO</balanceType>
			<percentWork>100</percentWork>
			<environmentType>ENV_PRODUCTION</environmentType>
			<version>9000</version>
		</hsmServer>
	</Servers>
</tns:ApiHSMConfig>
